captains_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('log.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

log/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:year>/<int:month>/<int:day>/', views.log_day, name='log_day'),
    path('todo', views.todo, name='todo'),
    path('done_todos', views.done_todos, name='done_todos'),
    path('export', views.csv_export, name='csv_export'),
    path('search', views.search, name='search'),
    path('helm', views.helm, name='helm'),
    path('log_all', views.log_list, name='log_list'),
    path('missions', views.mission_control, name='mission_control'),
    url('', include('django_prometheus.urls')),
]

log/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class CompleteableModel(models.Model):
    completeable = True
    completed_at = models.DateTimeField(null=True)
    wont_do = models.DateTimeField(null=True)

    class Meta:
        abstract = True

    def mark_complete(self):
        self.completed_at = timezone.now()
        self.save()

    def mark_wont(self):
        self.wont_do = timezone.now()
        self.save()

    def unmark_complete(self):
        self.completed_at = None
        self.wont_do = None
        self.save()

class Mission(CompleteableModel):
    name = models.CharField(max_length=255)
    notes = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class LogEntry(models.Model):
    text = models.TextField()
    event_date = models.DateField(default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='bullshit_name')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completeable = False
    mission = models.ForeignKey(Mission, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.text

class ToDoEntry(CompleteableModel):
    text = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    mission = models.ForeignKey(Mission, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

log/forms.py
from django import forms

from .models import LogEntry, ToDoEntry, Mission

class LogEntryForm(forms.ModelForm):
    text = forms.CharField(label='Entry', widget=forms.TextInput)

    class Meta:
        model = LogEntry
        fields = ('text',)

class ToDoForm(forms.ModelForm):
    text = forms.CharField(label='Entry', widget=forms.TextInput)

    class Meta:
        model = ToDoEntry
        fields = ('text',)

class MissionForm(forms.ModelForm):

    class Meta:
        model = Mission
        fields = ('name','notes')

log/views.py
import csv
import datetime

from django.shortcuts import render, get_object_or_404
from .models import LogEntry, ToDoEntry, Mission
from .forms import LogEntryForm, ToDoForm, MissionForm
from django.shortcuts import redirect
from django.http import HttpResponse
from django.db.models import Q

def helm(request):
    today = datetime.date.today()
    year, month, day = today.year, today.month, today.day
    if request.user.is_authenticated:
        if request.method == "POST":
            if request.POST['type'] == 'log':
                handle_post(request, (year, month, day))
            elif request.POST['type'] == 'todo':
                handle_post(request, klass=ToDoEntry, formKlass=ToDoForm)
            else:
                print("Unknown post type")

        unfinished_todos = ToDoEntry.objects.filter(completed_at__isnull=True, wont_do__isnull=True, author=request.user)
        existing_todo_forms = [ToDoForm(instance=li) for li in unfinished_todos]
        new_todo_form = ToDoForm()

        entries_for_day = LogEntry.objects.filter(event_date__exact=datetime.date(year, month, day), author=request.user)

        existing_log_forms = [LogEntryForm(instance=li) for li in entries_for_day]

        return render(request, 'log/helm.html', {'existing_logs': existing_log_forms, 'existing_todos': existing_todo_forms, 'date': (year, month, day)})
    else:
        return redirect('home')


def log_list(request):
    print(request)
    if request.method == "POST":
        handle_post(request)
    log_entries = LogEntry.objects.all();
    existing_forms = [LogEntryForm(instance=li) for li in log_entries]
    new_form = LogEntryForm()
    return render(request, 'log/log_list.html', {'new_form': new_form, 'existing_forms': existing_forms, 'date': []})

def home(request):
    return render(request, 'log/home.html')

def log_day(request, year, month, day):
    if request.user.is_authenticated:
        if request.method == "POST":
            handle_post(request, (year, month, day))

        entries_for_day = LogEntry.objects.filter(event_date__exact=datetime.date(year, month, day), author=request.user)

        existing_forms = [LogEntryForm(instance=li) for li in entries_for_day]
        new_form = LogEntryForm()
        return render(request, 'log/log_list.html', {'new_form': new_form, 'existing_forms': existing_forms, 'date': (year, month, day)})
    else:
        return redirect('home')

def handle_post(request, date=None, klass=LogEntry, formKlass=LogEntryForm):
    print(request.POST)
    if 'pk' in request.POST:
        post = get_object_or_404(klass, pk=request.POST['pk'])

    if 'delete_entry' in request.POST:
        post.delete()
        return
    elif 'mark_done' in request.POST:
        post.mark_complete()
        completed_message = 'Completed: ' + post.text if hasattr(post, 'text') else post.name
        LogEntry.objects.create(author=request.user, text=completed_message)
        return
    elif 'mark_wont' in request.POST:
        post.mark_wont()
        return
    elif 'undo' in request.POST:
        post.unmark_complete()
        return
    elif 'new_entry' in request.POST:
        form = formKlass(request.POST)
    elif 'update_entry' in request.POST:
        form = formKlass(request.POST, instance=post)
    else:
        print("Found unknown post: ", request.POST)
        return

    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        if date:
            year, month, day = date
            post.event_date = datetime.date(year, month, day)
        post.save()

def todo(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            handle_post(request, klass=ToDoEntry, formKlass=ToDoForm)
        unfinished_todos = ToDoEntry.objects.filter(completed_at__isnull=True, wont_do__isnull=True, author=request.user)
        existing_forms = [ToDoForm(instance=li) for li in unfinished_todos]
        new_form = ToDoForm()
        return render(request, 'log/log_list.html', {'new_form': new_form, 'existing_forms': existing_forms, 'title': "Todo"})
    else:
        return redirect('home')

def done_todos(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            handle_post(request, klass=ToDoEntry, formKlass=ToDoForm)
        finished_todos = ToDoEntry.objects.filter(Q(completed_at__isnull=False) | Q(wont_do__isnull=False), author=request.user)
        existing_forms = [ToDoForm(instance=li) for li in finished_todos]
        return render(request, 'log/log_list.html', {'existing_forms': existing_forms, 'title': "Past Todos"})
    else:
        return redirect('home')

def csv_export(request):
    all_log_entries = LogEntry.objects.filter(author=request.user)
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="captains_log.csv"'

    writer = csv.writer(response)
    columns = [field.name for field in all_log_entries[0]._meta.get_fields()]
    writer.writerow(columns)
    for entry in all_log_entries:
        row = [request.user.username if name=='author' else entry.serializable_value(name) for name in columns]
        writer.writerow(row)

    return response


def search(request):
    query_string = ''
    found_entries = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        entries = LogEntry.objects.filter(text__icontains=query_string).order_by('event_date')
        return render(request, 'log/home.html', { 'query_string': query_string, 'entries': entries })
    else:
        return render(request, 'log/home.html')

def mission_control(request):
    today = datetime.date.today()
    year, month, day = today.year, today.month, today.day
    if request.user.is_authenticated:
        if request.method == "POST":
            if request.POST['type'] == 'mission':
                handle_post(request, klass=Mission, formKlass=MissionForm)
            elif request.POST['type'] == 'log':
                handle_post(request, (year, month, day))
            elif request.POST['type'] == 'todo':
                handle_post(request, klass=Mission, formKlass=MissionForm)
            else:
                print("Unknown post type")

        unfinished_missions = Mission.objects.filter(completed_at__isnull=True, wont_do__isnull=True, author=request.user)
        existing_mission_forms = [MissionForm(instance=li) for li in unfinished_missions]
        new_mission_form = MissionForm()

        return render(request, 'log/mission_control.html', {'new_form': new_mission_form, 'existing_forms': existing_mission_forms, 'entry_type': 'mission', 'date': []})
    else:
        return redirect('home')

log/templates/log/base.html
{% load static %}
<!doctype html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/slate_theme.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/log.css' %}">
        <link rel="shortcut icon" type="image/png" href="https://comicmemories.altervista.org/images/favicon.png"/>

        <title>Captain's Log</title>
    </head>

    <body>
    <div class="container">
        <div class="d-flex p-2">
            <div class="mr-auto p-2"> <h1><a href="/">Captain's Log</a></h1></div>
            {% if user.is_authenticated %}
            <div class="p-2">{{ user.username }}</div>
            <div class="p-2"><a href="{% url 'logout' %}">logout</a></div>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
            {% block content %}
            {% endblock %}
        {% else %}
            <a href="/accounts/login">Login</a>
            <p><img src="https://i.pinimg.com/originals/59/d3/9b/59d39b53c37d0b18551971828873fb0f.png"/></p>
        {% endif %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script>function unhide(post_key)
    {
        var edit_form = document.getElementById("edit_"+post_key);
        edit_form.style.display="block";
        document.getElementById("title_"+post_key).style.display="none";
        edit_form.tabIndex = 0
        edit_form.focus();
    }
    function hide(post_key)
    {
        document.getElementById("edit_"+post_key).style.display="none";
        document.getElementById("title_"+post_key).style.display="block";
    }
    function next_day(year, month, day, delta){
        var current_day = new Date(year, month-1, day);
        current_day.setDate(current_day.getDate() + delta)
        var url_mask = "{% url 'log_day' year=9999 month=1111 day=2222 %}".replace(/9999/, current_day.getFullYear()).replace(/1111/, current_day.getMonth()+1).replace(/2222/, current_day.getDate());
        window.location.href = url_mask;
    }
    function today(){
        var current_day = new Date();
        var url_mask = "{% url 'log_day' year=9999 month=1111 day=2222 %}".replace(/9999/, current_day.getFullYear()).replace(/1111/, current_day.getMonth()+1).replace(/2222/, current_day.getDate());
        window.location.href = url_mask;
    }
    {% block scripts %}
    {% endblock %}
    </script>
    </body>
</html>

log/templates/log/completion_buttons.html
{% load template_tags %}

{% if entry.instance.completed_at or entry.instance.wont_do %}
    {% entry_button 'undo' 'Undo' entry.instance.pk %}
{% elif entry.instance.completeable %}
    {% entry_button 'mark_done' 'Done' entry.instance.pk %}
    {% entry_button 'mark_wont' "Won't Do" entry.instance.pk %}
{% endif %}

log/templates/log/day_based.html
{% extends 'log/base.html' %}
{% load template_tags %}

{% block content %}
    <div>
        <header class="day-header">
        <div class="d-flex align-items-center">
        <div class="mr-auto p-2" id="day-header">
        {% if date|length > 0 %}
            {{ date.1 }}-{{ date.2 }}-{{ date.0 }}
        {% endif %}
        {% if title %}
            {{ title }}
        {% endif %}
        </div>
        <div class="p-2">
        {% if date|length > 0 %}
            <a class="btn btn-sm btn-primary" href="javascript:next_day({{date.0}},{{date.1}},{{date.2}}, -1)"><i class="fas fa-angle-left"></i></a>
            <a class="btn btn-sm btn-primary" href="javascript:next_day({{date.0}},{{date.1}},{{date.2}}, 1)"><i class="fas fa-angle-right"></i></a>
            <a class="btn btn-sm btn-primary" href="javascript:today()">Today</a>
        {% else %}
            {% if request.path == "/todo" %}
                <a class="btn btn-sm btn-primary" href="{% url 'done_todos' %}">Done Todos</a>
            {% else %}
                <a class="btn btn-sm btn-primary" href="{% url 'todo' %}">Still todo</a>
            {% endif %}
        {% endif %}
        </div>
        </div>
        </header>
    </div>
    {% block day_content %}
    {% endblock %}

{% endblock %}

{% block scripts %}
    function keyupEvent(e, pk) {
        if(e.keyCode == 27){
            hide(pk);
        }
    }

    {% if date|length > 0 %}
    (function insertDayOfWeek() {
      var dayOfWeek = new Date({{date.0}},{{date.1}}-1,{{date.2}}).getDay();    
      var day = isNaN(dayOfWeek) ? null : ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][dayOfWeek];
      document.getElementById("day-header").insertAdjacentText("afterbegin", day + ", ");
    })();
    {% endif %}

{% endblock %}

log/templates/log/entries.html
{% load template_tags %}
<ul>
{% for entry in entries %}
<div>
    {% if entry.instance.wont_do %}
    <s>
    {% endif %}
    <li id=title_{{entry.instance.pk}}>
    {{ entry.instance.text }}
    {% if entry.instance.wont_do %}
    </s>
    {% endif %}
    {% if entry.instance.completed_at or entry.instance.wont_do %}
        {% entry_button 'undo' 'Undo' entry.instance.pk %}
    {% elif entry.instance.completeable %}
        {% entry_button 'mark_done' 'Done' entry.instance.pk %}
        {% entry_button 'mark_wont' "Won't Do" entry.instance.pk %}
    {% endif %}
    <a class="btn btn-sm btn-primary" href="javascript:unhide( {{entry.instance.pk}} )" style="display:inline"><i class="fas fa-edit"></i></a></li>
    <form method="POST" id=edit_{{entry.instance.pk}} class="edit-entry-form" onkeyup="keyupEvent(event, {{entry.instance.pk}})" style="display: none;">{% csrf_token %}
        {{ entry }}
        <input type="hidden" name="pk" value={{entry.instance.pk}}>
        <input type="hidden" name="type" value={{entry_type}}>
        <button type="submit" class="save btn btn-primary" onclick="hide({{entry.instance.pk}})" name="update_entry" value={{entry.instance.pk}}>Save</button>
        <button type="submit" class="save btn btn-danger" onclick="if (!confirm('Are you sure?')) return false;" name="delete_entry" value={{entry.instance.pk}}>Delete</button>
    </form>
</div>
{% endfor %}
</ul>

log/templates/log/helm.html
{% extends 'log/day_based.html' %}
{% load template_tags %}

{% block day_content %}
    <div class="entry-list pt-2">
        {% include "log/entries.html" with entries=existing_logs entry_type="log" %}
    </div>
    TODO:
    <div class="entry-list pt-2">
        {% include "log/entries.html" with entries=existing_todos entry_type="todo" %}
    </div>
    <div class="row">
    <div class="col-6">
        <p>
        <form method="POST" class="new-entry-form">{% csrf_token %}
            <label for="new-entry-text">New Entry:</label>
            <input type="hidden" name="new_entry">
            <input type="text" name="text" required id="new-entry-text">
            <button type="submit" class="save btn btn-primary" name="type" value="log">Save Log Entry</button>
            <button type="submit" class="save btn btn-primary" name="type" value="todo">Save Todo</button>
        </form>
        </p>
    </div>

{% endblock %}

log/templates/log/home.html
{% extends 'log/base.html' %}

{% block content %}

<div class='d-flex flex-row'>
<div class="p-2"><a class="btn btn-sm btn-primary" href="javascript:today()">Today</a></div>
<div class="p-2"><a class="btn btn-sm btn-primary" href="{% url 'todo' %}">Todo Items</a></div>
<div class="p-2"><a class="btn btn-sm btn-primary" href="{% url 'csv_export' %}">Export Data</a></div>
</div>

<form id="searchform" action="{% url 'search' %}" method="get">
    <input type="text" name="q" type="text"/>
    <button type="button" onclick="searchform.submit()">Search</button>
</form>

{% if entries|length > 0 %}
    <p>Entries containing '{{query_string}}'</p> 
    {% for entry in entries %}
        <div>
            <span> {{ entry.event_date }} </span>
            <a href="{{ entry.event_date|date:'Y/m/d' }}">{{ entry.text }}</a>
        </div>
    {% endfor %}
{% endif %}

{% endblock %}

log/templates/log/log_list.html
{% extends 'log/day_based.html' %}
{% load template_tags %}

{% block day_content %}
    <div class="entry-list pt-2">
        {% include "log/entries.html" with entries=existing_forms entry_type="unused" %}
    </div>
    <div class="row">
    <div class="col-6">
        <p>
        <form method="POST" class="new-entry-form">{% csrf_token %}
            <label for="{{ new_form.text.id_for_label }}">New Entry:</label>
            <input type="text" name="text" required id="new-entry-text">
            <button type="submit" class="save btn btn-primary" name="new_entry">Save</button>
        </form>
        </p>
    </div>
{% endblock %}

log/templates/log/mission_control.html
{% extends 'log/day_based.html' %}
{% load template_tags %}

{% block day_content %}
    <div class="accordion" id="mission-content">
        <ul>
        {% for entry in existing_forms %}
            <div class="card">
            <div class="card-header" id="heading{{entry.instance.pk}}">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse{{entry.instance.pk}}" aria-expanded="true" aria-controls="collapse{{entry.instance.pk}}">
                {{ entry.instance.name }}
                </button>
            </div>

            <div id="collapse{{entry.instance.pk}}" class="collapse" aria-labelledby="heading{{entry.instance.pk}}" data-parent="#mission-content">
            <div class="card-body">
                {{ entry.instance.notes }}

                {% for todo in entry.instance.todoentry_set.all %}
                    <li>{{todo}}</li>
                {% endfor %}

                {% include "log/completion_buttons.html" with entry=entry %}
                <a class="btn btn-sm btn-primary" href="javascript:unhide( {{entry.instance.pk}} )" style="display:inline"><i class="fas fa-edit"></i></a>
                <form method="POST" id=edit_{{entry.instance.pk}} class="edit-entry-form" onkeyup="keyupEvent(event, {{entry.instance.pk}})" style="display: none;">{% csrf_token %}
                {{ entry }}
                <input type="hidden" name="pk" value={{entry.instance.pk}}>
                <input type="hidden" name="type" value={{entry_type}}>
                <button type="submit" class="save btn btn-primary" onclick="hide({{entry.instance.pk}})" name="update_entry" value={{entry.instance.pk}}>Save</button>
                <button type="submit" class="save btn btn-danger" onclick="if (!confirm('Are you sure?')) return false;" name="delete_entry" value={{entry.instance.pk}}>Delete</button>
                </form>
            </div>
            </div>
            </div>
        {% endfor %}
    </div>
    <div class="row">
    <div class="col-6">
        <p>
        <form method="POST" class="new-entry-form">{% csrf_token %}
            <label for="{{ new_form.name.id_for_label }}">New Mission:</label>
            <input type="text" name="name" required id="new-entry-text">
            <label for="{{ new_form.notes.id_for_label }}">Notes:</label>
            <textarea type="textarea" name="notes" required id="new-entry-text"></textarea>
            <input type="hidden" name="type" value={{entry_type}}>
            <button type="submit" class="save btn btn-primary" name="new_entry">Save</button>
        </form>
        </p>
    </div>
{% endblock %}